name: Default
priority: 1
count: 0
maps:
- Warlock
- Flow
- Acear II
- Aaerhohohos
- Banana Unsplit
- Quench
- Grassy Mound
- Kaldr
- Snowy Wars Christmas
- Gralien
- Wrath Tor RAGE
- "Avalance: Mini"
- Mele Kalikimaka
- "BalloonsDTM: Christmas"
- Cerulean
- OutCast
- "Settler's Covert"
- Rotten
